/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.horvat.view;

import com.toedter.calendar.JCalendar;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javassist.Loader;
import javax.swing.ImageIcon;

/**
 *
 * @author Josip
 */
public class Izbornik extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Izbornik
     */
    ImageIcon pozadina = new ImageIcon("transportIzbornik.jpg");
    int sat,minuta,sekunda;
    
    public Izbornik() {
        initComponents();
             
        ucitajSliku();
        
        jmnIzbornik.setText(Aplikacija.NAZIV_APLIKACIJE);
        setTitle(Aplikacija.operater.getImeIPrezime());
        jmiOperateri.setVisible(Aplikacija.isAdmin());
        
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPozadina = new javax.swing.JPanel();
        lblPozadinskaSlika = new javax.swing.JLabel();
        lblSat = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmnIzbornik = new javax.swing.JMenu();
        jmiProizvodjaci = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiVozila = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiVozaci = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiZaduzenaVozila = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiPrijevoz = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiOperateri = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlPozadina.setBackground(new java.awt.Color(0, 0, 0));

        lblSat.setBackground(new java.awt.Color(0, 0, 0));
        lblSat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSat.setForeground(new java.awt.Color(255, 255, 255));
        lblSat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlPozadinaLayout = new javax.swing.GroupLayout(pnlPozadina);
        pnlPozadina.setLayout(pnlPozadinaLayout);
        pnlPozadinaLayout.setHorizontalGroup(
            pnlPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPozadinaLayout.createSequentialGroup()
                .addComponent(lblPozadinskaSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPozadinaLayout.setVerticalGroup(
            pnlPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPozadinaLayout.createSequentialGroup()
                .addComponent(lblPozadinskaSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPozadinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        jmnIzbornik.setForeground(new java.awt.Color(255, 255, 255));
        jmnIzbornik.setText("Izbornik");

        jmiProizvodjaci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiProizvodjaci.setText("Proizvodjaci");
        jmiProizvodjaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProizvodjaciActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiProizvodjaci);
        jmnIzbornik.add(jSeparator1);

        jmiVozila.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiVozila.setText("Vozila");
        jmiVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVozilaActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiVozila);
        jmnIzbornik.add(jSeparator2);

        jmiVozaci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiVozaci.setText("Vozaci");
        jmiVozaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVozaciActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiVozaci);
        jmnIzbornik.add(jSeparator6);

        jmiZaduzenaVozila.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiZaduzenaVozila.setText("Zaduzena vozila");
        jmiZaduzenaVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZaduzenaVozilaActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiZaduzenaVozila);
        jmnIzbornik.add(jSeparator3);

        jmiPrijevoz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiPrijevoz.setText("Prijevoz");
        jmiPrijevoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrijevozActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiPrijevoz);
        jmnIzbornik.add(jSeparator4);

        jmiOperateri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiOperateri.setText("Operateri");
        jmnIzbornik.add(jmiOperateri);
        jmnIzbornik.add(jSeparator5);

        jmiIzlaz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiIzlaz.setText("Izlaz");
        jmiIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlazActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiIzlaz);

        jMenuBar2.add(jmnIzbornik);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPozadina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPozadina, javax.swing.GroupLayout.PREFERRED_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_jmiIzlazActionPerformed

    private void jmiVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVozilaActionPerformed
        new Vozila().setVisible(true);
    }//GEN-LAST:event_jmiVozilaActionPerformed

    private void jmiVozaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVozaciActionPerformed
       new Vozaci().setVisible(true);
    }//GEN-LAST:event_jmiVozaciActionPerformed

    private void jmiZaduzenaVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZaduzenaVozilaActionPerformed
       new ZaduzenaVozila().setVisible(true);
    }//GEN-LAST:event_jmiZaduzenaVozilaActionPerformed

    private void jmiPrijevozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrijevozActionPerformed
       new PrijevozPutnika().setVisible(true);
    }//GEN-LAST:event_jmiPrijevozActionPerformed

    private void jmiProizvodjaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProizvodjaciActionPerformed
        new Proizvodjaci().setVisible(true);
    }//GEN-LAST:event_jmiProizvodjaciActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem jmiIzlaz;
    private javax.swing.JMenuItem jmiOperateri;
    private javax.swing.JMenuItem jmiPrijevoz;
    private javax.swing.JMenuItem jmiProizvodjaci;
    private javax.swing.JMenuItem jmiVozaci;
    private javax.swing.JMenuItem jmiVozila;
    private javax.swing.JMenuItem jmiZaduzenaVozila;
    private javax.swing.JMenu jmnIzbornik;
    private javax.swing.JLabel lblPozadinskaSlika;
    private javax.swing.JLabel lblSat;
    private javax.swing.JPanel pnlPozadina;
    // End of variables declaration//GEN-END:variables


    private void ucitajSliku(){
        Image image = pozadina.getImage();
       Image imageScale = image.getScaledInstance(lblPozadinskaSlika.getWidth(), lblPozadinskaSlika.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon = new ImageIcon(imageScale);
       lblPozadinskaSlika.setIcon(scaledIcon);
    } 

    @Override
    public void run() {
        while(true){
            Calendar cal = Calendar.getInstance();
            sat = cal.get(Calendar.HOUR_OF_DAY);
            minuta = cal.get(Calendar.MINUTE);
            sekunda = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            Date date = cal.getTime();
            String vrijeme24 = sdf.format(date);
            
            lblSat.setText(vrijeme24);
        }
    }

}
