/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.horvat.view;

import com.toedter.calendar.JCalendar;
import java.awt.BorderLayout;

/**
 *
 * @author Josip
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        Kalendar();
        
        jmnIzbornik.setText(Aplikacija.NAZIV_APLIKACIJE);
        setTitle(Aplikacija.operater.getImeIPrezime());
        jmiOperateri.setVisible(Aplikacija.isAdmin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPozadina = new javax.swing.JPanel();
        pnlKalendar = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmnIzbornik = new javax.swing.JMenu();
        jmiProizvodjaci = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiVozila = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiVozaci = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiPrijevoz = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiOperateri = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlKalendar.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlKalendarLayout = new javax.swing.GroupLayout(pnlKalendar);
        pnlKalendar.setLayout(pnlKalendarLayout);
        pnlKalendarLayout.setHorizontalGroup(
            pnlKalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        pnlKalendarLayout.setVerticalGroup(
            pnlKalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPozadinaLayout = new javax.swing.GroupLayout(pnlPozadina);
        pnlPozadina.setLayout(pnlPozadinaLayout);
        pnlPozadinaLayout.setHorizontalGroup(
            pnlPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPozadinaLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(pnlKalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlPozadinaLayout.setVerticalGroup(
            pnlPozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPozadinaLayout.createSequentialGroup()
                .addComponent(pnlKalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        jmnIzbornik.setForeground(new java.awt.Color(255, 255, 255));
        jmnIzbornik.setText("Izbornik");

        jmiProizvodjaci.setText("Proizvodjaci");
        jmiProizvodjaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProizvodjaciActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiProizvodjaci);
        jmnIzbornik.add(jSeparator1);

        jmiVozila.setText("Vozila");
        jmnIzbornik.add(jmiVozila);
        jmnIzbornik.add(jSeparator2);

        jmiVozaci.setText("Vozaci");
        jmnIzbornik.add(jmiVozaci);
        jmnIzbornik.add(jSeparator3);

        jmiPrijevoz.setText("Prijevoz");
        jmnIzbornik.add(jmiPrijevoz);
        jmnIzbornik.add(jSeparator4);

        jmiOperateri.setText("Operateri");
        jmnIzbornik.add(jmiOperateri);
        jmnIzbornik.add(jSeparator5);

        jmiIzlaz.setText("Izlaz");
        jmiIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlazActionPerformed(evt);
            }
        });
        jmnIzbornik.add(jmiIzlaz);

        jMenuBar2.add(jmnIzbornik);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_jmiIzlazActionPerformed

    private void jmiProizvodjaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProizvodjaciActionPerformed
       new Proizvodjaci().setVisible(true);
    }//GEN-LAST:event_jmiProizvodjaciActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem jmiIzlaz;
    private javax.swing.JMenuItem jmiOperateri;
    private javax.swing.JMenuItem jmiPrijevoz;
    private javax.swing.JMenuItem jmiProizvodjaci;
    private javax.swing.JMenuItem jmiVozaci;
    private javax.swing.JMenuItem jmiVozila;
    private javax.swing.JMenu jmnIzbornik;
    private javax.swing.JPanel pnlKalendar;
    private javax.swing.JPanel pnlPozadina;
    // End of variables declaration//GEN-END:variables

  private void Kalendar(){
        
        pnlKalendar.setLayout(new BorderLayout());
         
        JCalendar cal = new JCalendar();
        
        pnlKalendar.setLayout(new BorderLayout());
        pnlKalendar.add(cal,BorderLayout.CENTER);
        pnlKalendar.validate();
        
       }
}
