/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.horvat.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import hr.edunova.horvat.controller.ObradaVozilo;
import hr.edunova.horvat.model.Vozilo;
import hr.edunova.horvat.utility.MyException;
import java.awt.Component;
import java.awt.Image;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 * 
 * @author Josip
 */
public class Vozila extends javax.swing.JFrame {

    private ObradaVozilo obrada;
    private Vozilo entitet;
    
    ImageIcon createIcon = new ImageIcon("DatabaseDodajIcon.png");
    ImageIcon updateIcon = new ImageIcon("updateIcon.png");
    ImageIcon deleteIcon = new ImageIcon("deleteIcon.png");
    /**
     * Creates new form Vozila
     */
    public Vozila() {
        initComponents();
        obrada = new ObradaVozilo();
        setTitle(Aplikacija.operater.getImeIPrezime()+ " - Vozila ");
        ucitajPodatke();
       // ocistiPolja();
        dodajSliku();
        
        DatePickerSettings datePickerSettings = new DatePickerSettings(new Locale("hr", "HR"));
        datePickerSettings.setFormatForDatesCommonEra("dd.MM.yyyy");
        dpDatumProizvodnje.setSettings(datePickerSettings);
        
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        pnlPodaci = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtPrijedjeniKm = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblPoruka = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chbOsigurano = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtRegistracija = new javax.swing.JTextField();
        dpDatumProizvodnje = new com.github.lgooddatepicker.components.DatePicker();
        btnIzmijeni = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstPodaci.setBorder(new javax.swing.border.MatteBorder(null));
        lstPodaci.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lstPodaciMouseMoved(evt);
            }
        });
        lstPodaci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lstPodaciFocusLost(evt);
            }
        });
        lstPodaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPodaciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPodaci);

        pnlPodaci.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Naziv");

        txtModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPrijedjeniKm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtNaziv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Model");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Registracijska ");

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setText("Datum proizvodnje");

        lblPoruka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPoruka.setForeground(new java.awt.Color(204, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("oznaka");

        chbOsigurano.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chbOsigurano.setText("Osigurano");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ukupno Prijedjenih kilometara");

        txtRegistracija.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlPodaciLayout = new javax.swing.GroupLayout(pnlPodaci);
        pnlPodaci.setLayout(pnlPodaciLayout);
        pnlPodaciLayout.setHorizontalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(txtNaziv)
                            .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlPodaciLayout.createSequentialGroup()
                                    .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(91, 91, 91)
                                    .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl1)
                                        .addComponent(dpDatumProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPodaciLayout.createSequentialGroup()
                                    .addComponent(txtPrijedjeniKm, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chbOsigurano))))
                        .addContainerGap(86, Short.MAX_VALUE))))
        );
        pnlPodaciLayout.setVerticalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dpDatumProizvodnje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrijedjeniKm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbOsigurano, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        btnIzmijeni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIzmijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmijeniActionPerformed(evt);
            }
        });

        btnDodaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnIzmijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzmijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstPodaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPodaciValueChanged
      if(evt.getValueIsAdjusting()){
          return;
      }
      entitet=lstPodaci.getSelectedValue();
      if(entitet== null){
          return;
      }
      // potencijalno bolje rješenje je korištenje Reflection API
        //https://docs.oracle.com/javase/tutorial/reflect/index.html
        
        txtNaziv.setText(entitet.getNaziv());
        txtModel.setText(entitet.getModel());
        txtPrijedjeniKm.setText(entitet.getUkupnoPredjenihKm().toString());
        txtRegistracija.setText(entitet.getRegistracijskaOznaka());
        chbOsigurano.setSelected(entitet.getOsigurano());
        
        dpDatumProizvodnje.setDate(entitet.getDatumProizvodnje().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate());
        
        
        
        
        
    }//GEN-LAST:event_lstPodaciValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
       
        lblPoruka.setText("");
        entitet = new Vozilo();
        
        postaviVrijednostiUEntitet();
        
      try {
            obrada.create();
            ucitajPodatke();
            ocistiPolja();
        } catch (MyException ex) {
           lblPoruka.setText(ex.getPoruka());
        }           
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmijeniActionPerformed
      entitet= lstPodaci.getSelectedValue();
      if(entitet==null){
          return;
      }
      postaviVrijednostiUEntitet();
      
      try{
          obrada.update();
          ucitajPodatke();
          ocistiPolja();
      }catch(MyException e){
          lblPoruka.setText(e.getPoruka());
      }
        
    }//GEN-LAST:event_btnIzmijeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        entitet= lstPodaci.getSelectedValue();
          if(entitet==null){
            return;
         }
          obrada.setEntitet(entitet);
        
        try{
          obrada.delete();
          ucitajPodatke();
          ocistiPolja();
      }catch(MyException e){
          lblPoruka.setText(e.getPoruka());
      }
       
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void lstPodaciMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPodaciMouseMoved

    }//GEN-LAST:event_lstPodaciMouseMoved

    private void lstPodaciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lstPodaciFocusLost
        
    }//GEN-LAST:event_lstPodaciFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmijeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JCheckBox chbOsigurano;
    private com.github.lgooddatepicker.components.DatePicker dpDatumProizvodnje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JList<Vozilo> lstPodaci;
    private javax.swing.JPanel pnlPodaci;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPrijedjeniKm;
    private javax.swing.JTextField txtRegistracija;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {

        DefaultListModel<Vozilo> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(s-> m.addElement(s));
        // Za svaki s, model dodaj mi element tog s iz obrada(Obrada Vozilo)
        // Ovaj forEach  je  one liner koji zamjenjuje petlje 
        
        lstPodaci.setModel(m);
        // ispravak greske na m: Design-> lstPodaci->code-> TypeParametars postaviti u vozilo
    }
    
    public void dodajSliku(){
      
       Image image = createIcon.getImage();
       Image imageScale = image.getScaledInstance(btnDodaj.getWidth(), btnDodaj.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon = new ImageIcon(imageScale);
       btnDodaj.setIcon(scaledIcon);
       
       Image image1 = updateIcon.getImage();
       Image imageScale1 = image1.getScaledInstance(btnIzmijeni.getWidth(), btnIzmijeni.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon1 = new ImageIcon(imageScale1);
       btnIzmijeni.setIcon(scaledIcon1);
       
       Image image2 = deleteIcon.getImage();
       Image imageScale2 = image2.getScaledInstance(btnObrisi.getWidth(), btnObrisi.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon2 = new ImageIcon(imageScale2);
       btnObrisi.setIcon(scaledIcon2);
    }

    private void ocistiPolja() {
   // Ako imas puno atributa mozes koristiti Component da bi si ustedio vrijeme.
        for(Component c: pnlPodaci.getComponents()){
            if( c instanceof JTextField){
                ((JTextField) c).setText("");
            }
            if(c instanceof JCheckBox){
                ((JCheckBox) c).setSelected(false);
            }
        }
           dpDatumProizvodnje.setDate(LocalDate.now());
        
//        txtNaziv.setText("");
//        txtModel.setText("");
//        txtRegistracija.setText("");
//        txtPrijedjeniKm.setText("");
//        txtDatumProizvodnje.setText("");
//        chbOsigurano.setSelected(false);
        

        
    }

    private void postaviVrijednostiUEntitet() {

        entitet.setNaziv(txtNaziv.getText());
        entitet.setModel(txtModel.getText());
        entitet.setRegistracijskaOznaka(txtRegistracija.getText());
        entitet.setOsigurano(chbOsigurano.isSelected());
        
        try{
        entitet.setUkupnoPredjenihKm(new BigDecimal (txtPrijedjeniKm.getText()));  
        }catch(Exception e){
            entitet.setUkupnoPredjenihKm(BigDecimal.ZERO);
        }
        try{
        entitet.setDatumProizvodnje(Date.from(dpDatumProizvodnje.getDate().atStartOfDay()
        .atZone(ZoneId.systemDefault())
        .toInstant()));
        }catch(Exception e){
            entitet.setDatumProizvodnje(null);
        }
       obrada.setEntitet(entitet);
        
    }
}
