/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.horvat.view;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import hr.edunova.horvat.controller.ObradaVozac;
import hr.edunova.horvat.controller.ObradaVozilo;
import hr.edunova.horvat.controller.ObradaZaduzenoVozilo;
import hr.edunova.horvat.model.Vozac;
import hr.edunova.horvat.model.Vozilo;
import hr.edunova.horvat.model.ZaduzenoVozilo;
import hr.edunova.horvat.utility.MyException;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Josip
 */
public class ZaduzenaVozila extends javax.swing.JFrame {
    
    ImageIcon createIcon = new ImageIcon("DatabaseDodajIcon.png");
    ImageIcon updateIcon = new ImageIcon("updateIcon.png");
    ImageIcon deleteIcon = new ImageIcon("deleteIcon.png");
    ImageIcon searchIcon = new ImageIcon("searchIcon.png");

    private ObradaZaduzenoVozilo obrada;
    private ZaduzenoVozilo entitet;

    /**
     * Creates new form ZaduzenaVozila
     */
    public ZaduzenaVozila() {
        initComponents();
        obrada = new ObradaZaduzenoVozilo();
        setTitle(Aplikacija.operater.getImeIPrezime() + " -Zaduzena vozila");
        dodajSliku();
      pnlDatePicker.setVisible(false);

        DefaultComboBoxModel<Vozilo> modelVozilo = new DefaultComboBoxModel<>();
        new ObradaVozilo().getPodaci().forEach(s -> {
            modelVozilo.addElement(s);
        });
        cmbVozilo.setModel(modelVozilo);

        DefaultComboBoxModel<Vozac> modelVozac = new DefaultComboBoxModel<>();
        new ObradaVozac().getPodaci().forEach(j -> {
            modelVozac.addElement(j);
        });
        cmbVozac.setModel(modelVozac);

        DatePickerSettings dps = new DatePickerSettings(new Locale("hr", "HR"));
        dps.setFormatForDatesCommonEra("dd.MM.yyyy");
        dpUnesiDatum.setSettings(dps);
        
        ucitajPodatke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKontrolnoPolje = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbVozac = new javax.swing.JComboBox<>();
        cmbVozilo = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        btnIzmijeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        rbtnRazduziVozilo = new javax.swing.JRadioButton();
        rbtnZaduziVozilo = new javax.swing.JRadioButton();
        pnlDatePicker = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dpUnesiDatum = new com.github.lgooddatepicker.components.DatePicker();
        lblPoruka = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneZaduzenoRazduzeno = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRazduzenaVozila = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstZaduzenaVozila = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Vozilo");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setText("Vozac");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnDodaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmijeni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIzmijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmijeniActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        rbtnRazduziVozilo.setText("Razduzi vozilo");
        rbtnRazduziVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRazduziVoziloActionPerformed(evt);
            }
        });

        rbtnZaduziVozilo.setText("Zaduzi vozilo");
        rbtnZaduziVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnZaduziVoziloActionPerformed(evt);
            }
        });

        jLabel2.setText("Upisi Datum");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlDatePickerLayout = new javax.swing.GroupLayout(pnlDatePicker);
        pnlDatePicker.setLayout(pnlDatePickerLayout);
        pnlDatePickerLayout.setHorizontalGroup(
            pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatePickerLayout.createSequentialGroup()
                .addGroup(pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatePickerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dpUnesiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatePickerLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatePickerLayout.setVerticalGroup(
            pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatePickerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpUnesiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(txtPaneZaduzenoRazduzeno);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" Zaduzeno/Razduzeno Vozilo");

        javax.swing.GroupLayout pnlKontrolnoPoljeLayout = new javax.swing.GroupLayout(pnlKontrolnoPolje);
        pnlKontrolnoPolje.setLayout(pnlKontrolnoPoljeLayout);
        pnlKontrolnoPoljeLayout.setHorizontalGroup(
            pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnRazduziVozilo)
                    .addComponent(rbtnZaduziVozilo))
                .addGap(37, 37, 37)
                .addComponent(pnlDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlKontrolnoPoljeLayout.setVerticalGroup(
            pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addComponent(rbtnZaduziVozilo)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnRazduziVozilo)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addComponent(pnlDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmijeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        lstRazduzenaVozila.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRazduzenaVozilaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRazduzenaVozila);

        lstZaduzenaVozila.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZaduzenaVozilaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstZaduzenaVozila);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKontrolnoPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pnlKontrolnoPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        lblPoruka.setText("");
        entitet = new ZaduzenoVozilo();

        postaviVrijednostiUEntitet();

        try {
            obrada.create();
            ucitajPodatke();
            ocistiPolja();
        } catch (MyException e) {
            lblPoruka.setText(e.getPoruka());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmijeniActionPerformed
        lblPoruka.setText("");
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        postaviVrijednostiUEntitet();

        try {
            obrada.update();
            ucitajPodatke();
            ocistiPolja();
        } catch (MyException e) {
            lblPoruka.setText(e.getPoruka());
        }

    }//GEN-LAST:event_btnIzmijeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            ocistiPolja();
        } catch (MyException e) {
            lblPoruka.setText(e.getPoruka());
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void rbtnRazduziVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRazduziVoziloActionPerformed
        pnlDatePicker.setVisible(true);
        if (!rbtnRazduziVozilo.isSelected()) {
            pnlDatePicker.setVisible(false);
        }
        if (rbtnRazduziVozilo.isSelected()) {
            rbtnZaduziVozilo.setSelected(false);
        }
    }//GEN-LAST:event_rbtnRazduziVoziloActionPerformed

    private void rbtnZaduziVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnZaduziVoziloActionPerformed
        pnlDatePicker.setVisible(true);
        if (!rbtnZaduziVozilo.isSelected()) {
            pnlDatePicker.setVisible(false);
        }
        if (rbtnZaduziVozilo.isSelected()) {
            rbtnRazduziVozilo.setSelected(false);
        }
       
    }//GEN-LAST:event_rbtnZaduziVoziloActionPerformed

    private void lstRazduzenaVozilaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRazduzenaVozilaValueChanged

          if (evt.getValueIsAdjusting()) {
            return;
        }
        
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        
        DefaultComboBoxModel<Vozac> v = (DefaultComboBoxModel<Vozac>) cmbVozac.getModel();
        for (int i = 0; i < v.getSize(); i++){
            if(v.getElementAt(i).getId().equals(entitet.getVozac().getId())){
                cmbVozac.setSelectedIndex(i);
                break;
            }
        }
        
          DefaultComboBoxModel<Vozilo> vozilo = (DefaultComboBoxModel<Vozilo>) cmbVozilo.getModel();
        for (int i = 0; i < vozilo.getSize(); i++){
            if(vozilo.getElementAt(i).getId().equals(entitet.getVozilo().getId())){
                cmbVozilo.setSelectedIndex(i);
                break;
            }
        
    }                               

    }//GEN-LAST:event_lstRazduzenaVozilaValueChanged

    private void lstZaduzenaVozilaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZaduzenaVozilaValueChanged
         if (evt.getValueIsAdjusting()) {
            return;
        }
        
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        
        DefaultComboBoxModel<Vozac> v = (DefaultComboBoxModel<Vozac>) cmbVozac.getModel();
        for (int i = 0; i < v.getSize(); i++){
            if(v.getElementAt(i).getId().equals(entitet.getVozac().getId())){
                cmbVozac.setSelectedIndex(i);
                break;
            }
        }
        
          DefaultComboBoxModel<Vozilo> vozilo = (DefaultComboBoxModel<Vozilo>) cmbVozilo.getModel();
        for (int i = 0; i < vozilo.getSize(); i++){
            if(vozilo.getElementAt(i).getId().equals(entitet.getVozilo().getId())){
                cmbVozilo.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_lstZaduzenaVozilaValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmijeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JComboBox<Vozac> cmbVozac;
    private javax.swing.JComboBox<Vozilo> cmbVozilo;
    private com.github.lgooddatepicker.components.DatePicker dpUnesiDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JList<ZaduzenoVozilo> lstRazduzenaVozila;
    private javax.swing.JList<ZaduzenoVozilo> lstZaduzenaVozila;
    private javax.swing.JPanel pnlDatePicker;
    private javax.swing.JPanel pnlKontrolnoPolje;
    private javax.swing.JRadioButton rbtnRazduziVozilo;
    private javax.swing.JRadioButton rbtnZaduziVozilo;
    private javax.swing.JTextPane txtPaneZaduzenoRazduzeno;
    // End of variables declaration//GEN-END:variables

    private void postaviVrijednostiUEntitet() {

        entitet.setVozac((Vozac) cmbVozac.getSelectedItem());
        entitet.setVozilo((Vozilo) cmbVozilo.getSelectedItem());

        if (rbtnZaduziVozilo.isSelected()) {
            try {
                entitet.setVoziloZaduzeno(Date.from(dpUnesiDatum.getDate().atStartOfDay()
                        .atZone(ZoneId.systemDefault())
                        .toInstant()));
                entitet.setVoziloRazduzeno(null);
            } catch (Exception e) {
                entitet.setVoziloZaduzeno(null);
            }

        }

        if (rbtnRazduziVozilo.isSelected()) {

            try {
                entitet.setVoziloRazduzeno(Date.from(dpUnesiDatum.getDate().atStartOfDay()
                        .atZone(ZoneId.systemDefault())
                        .toInstant()));
            } catch (Exception f) {
                entitet.setVoziloRazduzeno(null);
            }
        }
           
        obrada.setEntitet(entitet);

    }

    private void ucitajPodatke() {
        DefaultListModel<ZaduzenoVozilo> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(s -> m.addElement(s));
       
        lstZaduzenaVozila.setModel(m);
        
        }

    private void ocistiPolja() {
        dpUnesiDatum.clear();

    }
     public void dodajSliku(){
      
       Image image = createIcon.getImage();
       Image imageScale = image.getScaledInstance(btnDodaj.getWidth(), btnDodaj.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon = new ImageIcon(imageScale);
       btnDodaj.setIcon(scaledIcon);
       
       Image image1 = updateIcon.getImage();
       Image imageScale1 = image1.getScaledInstance(btnIzmijeni.getWidth(), btnIzmijeni.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon1 = new ImageIcon(imageScale1);
       btnIzmijeni.setIcon(scaledIcon1);
       
       Image image2 = deleteIcon.getImage();
       Image imageScale2 = image2.getScaledInstance(btnObrisi.getWidth(), btnObrisi.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon  scaledIcon2 = new ImageIcon(imageScale2);
       btnObrisi.setIcon(scaledIcon2);
     }
}
