/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.horvat.view;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import hr.edunova.horvat.controller.ObradaVozac;
import hr.edunova.horvat.controller.ObradaVozilo;
import hr.edunova.horvat.controller.ObradaZaduzenoVozilo;
import hr.edunova.horvat.model.Vozac;
import hr.edunova.horvat.model.Vozilo;
import hr.edunova.horvat.model.ZaduzenoVozilo;
import hr.edunova.horvat.utility.MyException;
import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Josip
 */
public class ZaduzenaVozila extends javax.swing.JFrame {
//    "slike"+ File.separator+ "vozaci"+ 
//                File.separator + entitet.getId()+ ".png");
     
    ImageIcon deleteIcon = new ImageIcon("slike"+ File.separator+ "ikonice" + File.separator+ "deleteIcon.png");
    ImageIcon zaduziVoziloIcon = new ImageIcon("slike"+ File.separator+ "ikonice" + File.separator+"ZaduziVozilo.png");
    ImageIcon razduziVoziloIcon = new ImageIcon("slike"+ File.separator+ "ikonice" + File.separator+"razduziVozilo.png");
      
    private ObradaZaduzenoVozilo obrada;
    private ZaduzenoVozilo entitet;

    /**
     * Creates new form ZaduzenaVozila
     */
    public ZaduzenaVozila() {
        initComponents();
        obrada = new ObradaZaduzenoVozilo();
        setTitle(Aplikacija.operater.getImeIPrezime() + " -Zaduzena vozila");
        dodajSliku();
        pnlDatePicker.setVisible(false);
        
        DefaultComboBoxModel<Vozilo> modelVozilo = new DefaultComboBoxModel<>();
        new ObradaVozilo().getPodaci().forEach(s -> {
            modelVozilo.addElement(s);
        });
        cmbVozilo.setModel(modelVozilo);
        
        DefaultComboBoxModel<Vozac> modelVozac = new DefaultComboBoxModel<>();
        List<Vozac> lista =  new ObradaVozac().getPodaci();
        Collections.sort(lista,new Comparator<Vozac>(){
            @Override
            public int compare(Vozac o1, Vozac o2) {
           return o1.getPrezime().compareTo(o2.getPrezime());
            }
        
        });
      
         lista.forEach(p-> {modelVozac.addElement(p);
         
         });
               
        cmbVozac.setModel(modelVozac);
        
        DatePickerSettings dps = new DatePickerSettings(new Locale("hr", "HR"));
        dps.setFormatForDatesCommonEra("dd.MM.yyyy");
        dpUnesiDatum.setSettings(dps);
        
        ucitajPodatke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKontrolnoPolje = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbVozac = new javax.swing.JComboBox<>();
        cmbVozilo = new javax.swing.JComboBox<>();
        btnZaduzi = new javax.swing.JButton();
        btnRazduzi = new javax.swing.JButton();
        rbtnRazduziVozilo = new javax.swing.JRadioButton();
        rbtnZaduziVozilo = new javax.swing.JRadioButton();
        pnlDatePicker = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dpUnesiDatum = new com.github.lgooddatepicker.components.DatePicker();
        lblPoruka = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRazduzenaVozila = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstZaduzenaVozila = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Vozilo");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setText("Vozac");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cmbVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVoziloActionPerformed(evt);
            }
        });

        btnZaduzi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        btnRazduzi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        rbtnRazduziVozilo.setText("Razduzi vozilo");
        rbtnRazduziVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRazduziVoziloActionPerformed(evt);
            }
        });

        rbtnZaduziVozilo.setText("Zaduzi vozilo");
        rbtnZaduziVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnZaduziVoziloActionPerformed(evt);
            }
        });

        jLabel2.setText("Upisi Datum");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlDatePickerLayout = new javax.swing.GroupLayout(pnlDatePicker);
        pnlDatePicker.setLayout(pnlDatePickerLayout);
        pnlDatePickerLayout.setHorizontalGroup(
            pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatePickerLayout.createSequentialGroup()
                .addGroup(pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatePickerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dpUnesiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatePickerLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatePickerLayout.setVerticalGroup(
            pnlDatePickerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatePickerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpUnesiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblPoruka.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setText(" Zaduzeno/Razduzeno Vozilo");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setText("vozila.");

        btnObrisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel6.setText("Ukloni iz povijesti razduzenih ");

        javax.swing.GroupLayout pnlKontrolnoPoljeLayout = new javax.swing.GroupLayout(pnlKontrolnoPolje);
        pnlKontrolnoPolje.setLayout(pnlKontrolnoPoljeLayout);
        pnlKontrolnoPoljeLayout.setHorizontalGroup(
            pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                                .addComponent(pnlDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontrolnoPoljeLayout.createSequentialGroup()
                                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18))
                                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)))
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(rbtnZaduziVozilo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnRazduziVozilo)
                .addGap(54, 54, 54))
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnZaduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRazduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        pnlKontrolnoPoljeLayout.setVerticalGroup(
            pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnZaduziVozilo)
                    .addComponent(rbtnRazduziVozilo))
                .addGap(18, 18, 18)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZaduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRazduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlKontrolnoPoljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlKontrolnoPoljeLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        lstRazduzenaVozila.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstRazduzenaVozila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRazduzenaVozilaMouseClicked(evt);
            }
        });
        lstRazduzenaVozila.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRazduzenaVozilaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRazduzenaVozila);

        lstZaduzenaVozila.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstZaduzenaVozila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstZaduzenaVozilaMouseClicked(evt);
            }
        });
        lstZaduzenaVozila.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZaduzenaVozilaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstZaduzenaVozila);

        jLabel7.setText("Zaduzena vozila");

        jLabel8.setText("Razduzena vozila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKontrolnoPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlKontrolnoPolje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed
        
        lblPoruka.setText("");
        entitet = new ZaduzenoVozilo();
        
        postaviVrijednostiUEntitet();
        
        try {
            obrada.create();
            ucitajPodatke();
            ocistiPolja();
        } catch (MyException e) {
           postaviPoruku(e.getPoruka());
        }
    }//GEN-LAST:event_btnZaduziActionPerformed

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed
        lblPoruka.setText("");
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }       
        postaviVrijednostiUEntitet();
        
        try {
              if(dpUnesiDatum.getDate()== null){
             throw new MyException ("Unesi datum razduzivanja vozila");
              }   
            obrada.update();
            ucitajPodatke();
            ocistiPolja(); 
           lblPoruka.setText("");
        } catch (MyException e) {
           postaviPoruku(e.getPoruka());
        }
               
    }//GEN-LAST:event_btnRazduziActionPerformed

     private void postaviPoruku(String poruka ){
        lblPoruka.setText(poruka);
        OcistiPoruku op = new OcistiPoruku();
        op.start();
      
    }
    
    private class OcistiPoruku extends Thread{

        @Override
        public void run() {
          try {
            Thread.sleep(3*1000);
        } catch (InterruptedException ex) {
      
        }
          lblPoruka.setText("");
        }
        
    }
    
    private void rbtnRazduziVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRazduziVoziloActionPerformed
        pnlDatePicker.setVisible(true);
        if (!rbtnRazduziVozilo.isSelected()) {
            pnlDatePicker.setVisible(false);
        }
        if (rbtnRazduziVozilo.isSelected()) {
            rbtnZaduziVozilo.setSelected(false);
        }
    }//GEN-LAST:event_rbtnRazduziVoziloActionPerformed

    private void rbtnZaduziVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnZaduziVoziloActionPerformed
        pnlDatePicker.setVisible(true);
        if (!rbtnZaduziVozilo.isSelected()) {
            pnlDatePicker.setVisible(false);
        }
        if (rbtnZaduziVozilo.isSelected()) {
            rbtnRazduziVozilo.setSelected(false);
        }
        
    }//GEN-LAST:event_rbtnZaduziVoziloActionPerformed

    private void lstRazduzenaVozilaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRazduzenaVozilaValueChanged
        
        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        entitet = lstRazduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        
        DefaultComboBoxModel<Vozac> v = (DefaultComboBoxModel<Vozac>) cmbVozac.getModel();
        for (int i = 0; i < v.getSize(); i++) {
            if (v.getElementAt(i).getId().equals(entitet.getVozac().getId())) {
                cmbVozac.setSelectedIndex(i);
                break;
            }
        }
        
        DefaultComboBoxModel<Vozilo> vozilo = (DefaultComboBoxModel<Vozilo>) cmbVozilo.getModel();
        for (int i = 0; i < vozilo.getSize(); i++) {
            if (vozilo.getElementAt(i).getId().equals(entitet.getVozilo().getId())) {
                cmbVozilo.setSelectedIndex(i);
                break;
            }
            
        }        

    }//GEN-LAST:event_lstRazduzenaVozilaValueChanged

    private void lstZaduzenaVozilaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZaduzenaVozilaValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        entitet = lstZaduzenaVozila.getSelectedValue();
        if (entitet == null) {
            return;
        }
        
        DefaultComboBoxModel<Vozac> v = (DefaultComboBoxModel<Vozac>) cmbVozac.getModel();
        for (int i = 0; i < v.getSize(); i++) {
            if (v.getElementAt(i).getId().equals(entitet.getVozac().getId())) {
                cmbVozac.setSelectedIndex(i);
                break;
            }
        }
        
        DefaultComboBoxModel<Vozilo> vozilo = (DefaultComboBoxModel<Vozilo>) cmbVozilo.getModel();
        for (int i = 0; i < vozilo.getSize(); i++) {
            if (vozilo.getElementAt(i).getId().equals(entitet.getVozilo().getId())) {
                cmbVozilo.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_lstZaduzenaVozilaValueChanged

    private void lstZaduzenaVozilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstZaduzenaVozilaMouseClicked
     
    }//GEN-LAST:event_lstZaduzenaVozilaMouseClicked

    private void lstRazduzenaVozilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRazduzenaVozilaMouseClicked
  
    }//GEN-LAST:event_lstRazduzenaVozilaMouseClicked

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        entitet= lstRazduzenaVozila.getSelectedValue();
        if(entitet==null){
            return;
        }
        obrada.setEntitet(entitet);

        try{
            obrada.delete();
            ucitajPodatke();
            ocistiPolja();
        }catch(MyException e){
            postaviPoruku(e.getPoruka());
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void cmbVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVoziloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVoziloActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JComboBox<Vozac> cmbVozac;
    private javax.swing.JComboBox<Vozilo> cmbVozilo;
    private com.github.lgooddatepicker.components.DatePicker dpUnesiDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JList<ZaduzenoVozilo> lstRazduzenaVozila;
    private javax.swing.JList<ZaduzenoVozilo> lstZaduzenaVozila;
    private javax.swing.JPanel pnlDatePicker;
    private javax.swing.JPanel pnlKontrolnoPolje;
    private javax.swing.JRadioButton rbtnRazduziVozilo;
    private javax.swing.JRadioButton rbtnZaduziVozilo;
    // End of variables declaration//GEN-END:variables

    private void postaviVrijednostiUEntitet() {
        
        entitet.setVozac((Vozac) cmbVozac.getSelectedItem());
        entitet.setVozilo((Vozilo) cmbVozilo.getSelectedItem());
        
        if (rbtnZaduziVozilo.isSelected()) {
            try {
                entitet.setVoziloZaduzeno(Date.from(dpUnesiDatum.getDate().atStartOfDay()
                        .atZone(ZoneId.systemDefault())
                        .toInstant()));
                entitet.setVoziloRazduzeno(null);
            } catch (Exception e) {
                entitet.setVoziloZaduzeno(null);
            }
            
        }
        
        if (rbtnRazduziVozilo.isSelected()) {
            
            try {
                entitet.setVoziloRazduzeno(Date.from(dpUnesiDatum.getDate().atStartOfDay()
                        .atZone(ZoneId.systemDefault())
                        .toInstant()));               
            } catch (Exception f) {
                entitet.setVoziloRazduzeno(null);
            }
        }
        
        obrada.setEntitet(entitet);
        
    }
    
    private void ucitajPodatke() {
        DefaultListModel<ZaduzenoVozilo> mZaduzeno = new DefaultListModel<>();
        DefaultListModel<ZaduzenoVozilo> mRazduzeno = new DefaultListModel<>();
        
        List<ZaduzenoVozilo> lista = obrada.getPodaci();
        
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).getVoziloRazduzeno() == null) {
                mZaduzeno.addElement(lista.get(i));
            } else {
                mRazduzeno.addElement(lista.get(i));
            }
                  }
        lstRazduzenaVozila.setModel(mRazduzeno);
        lstZaduzenaVozila.setModel(mZaduzeno);     
    }
    
    private void ocistiPolja() {
        dpUnesiDatum.clear();
        
    }
    
    public void dodajSliku() {
        
        Image image2 = deleteIcon.getImage();
        Image imageScale2 = image2.getScaledInstance(btnObrisi.getWidth(), btnObrisi.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(imageScale2);
        btnObrisi.setIcon(scaledIcon2);
        
        Image image = zaduziVoziloIcon.getImage();
        Image imageScale = image.getScaledInstance(btnZaduzi.getWidth(), btnZaduzi.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScale);
        btnZaduzi.setIcon(scaledIcon);
        
        Image image1 = razduziVoziloIcon.getImage();
        Image imageScale1 = image1.getScaledInstance(btnRazduzi.getWidth(), btnRazduzi.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(imageScale1);
        btnRazduzi.setIcon(scaledIcon1);
    }
}
